
spring:
  application:
    name: ${APP_NAME:spring-boot-rabbitmq-demo}

  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USERNAME:guest}
    password: ${RABBITMQ_PASSWORD:guest}

  data:
    redis:
      repositories:
        enabled: false
  redis:
    host: ${REDIS_HOST:localhost}
    port: ${REDIS_PORT:6379}
    password: ${REDIS_PASSWORD:}

server:
  port: ${PORT:8080}

runner: ${RUNNER:true}